name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Set the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
        
    - name: Deploy
      run: npm run deploy　　 　
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates this secret to use in your workflow
